name: PerchVillagerOptimisation
version: '${project.version}'
main: me.perch.VillagerOptimisation
api-version: '1.20'
authors: [ RebelMythik, CaveRaider, KayaLambrex]
description: Bonk Villagers

commands:
  pvoreload:
    description: "Reloads the pvo plugin"
    usage: "/pvoreload"
    permission: pvo.reload
  pvooptimize:
    description: "Will optimize all villagers within a configurable radius by renaming them"
    usage: "/pvooptimize"
    permission: pvo.optimize
  pvounoptimize:
    description: "Will unoptimize all villagers within a configurable radius by renaming them"
    usage: "/pvounoptimize"
    permission: pvo.unoptimize
  pvoremove:
    description: "Will remove all changes done by the plugin server wide"
    usage: "/pvoremove"
    permission: pvo.remove

permissions:
  pvo.cooldown.bypass:
    default: false
  pvo.message.nextrestock:
    default: true
  pvo.restockcooldown.bypass:
    default: false
  pvo.notify.update:
    op: true